dataset = {
	"acne": ["itchy skin", "whiteheads", "skin inflammation", "clogged pores"],
	"alcoholic_hepatitis": ["abdominal pain", "swelling in abdomen", "weight loss", "itchy skin", "dark colored urine"],
    "arthritis": ["limited range of motion", "joint deformities", "morning stiffness", "joint tenderness", "weight loss"],
    "cervical_spondylosis": ["neck pain", "numbness in arms, hands, legs, or feet", "lack of coordination", "muscle spasms", "tingling", "muscle weakness", "difficulty walking", "dizziness"],
    "chickenpox": ["itchy rash", "fluid filled blisters", "malaise", "muscle pain", "sore throat", "irritability"],
    "chronic_cholestasis": ["confusion", "dark urine", "pale stools", "itchy skin", "clay colored stools", "yellowing of mucous membranes"],
    "common_cold": ["runny nose", "sneezing", "throat irritation", "body aches", "chills", "sore throat", "watery eyes", "nose congestion", "general malaise"],
    "dengue": ["skin rash", "muscle pain", "bleeding gums", "vomiting blood", "low platelet count"],
    "diabetes": ["increased thirst", "frequent urination", "unexplained weight loss", "blurred vision", "slow wound healing", "numbness or tingling in extremities", "frequent infections", "skin infections", "dry mouth"],
    "dimorphic_hemorrhoids": ["rectal bleeding", "pain", "anal itching", "lump near anus", "fecal leakage", "swollen veins", "discomfort during bowel movements", "mucous discharge", "protruding lumps", "incomplete bowel movements"],
    "drug_reaction": ["itching", "shortness of breath", "blistering", "peeling", "hives"],
    "fungal_infection": ["redness", "skin peeling", "cracking of skin", "burning sensation", "unusual nail changes", "thickened skin", "yellow toenails", "itchy scalp", "white patches on skin"],
    "gerd": ["acid reflux", "difficulty swallowing", "dry cough", "hoarseness", "regurgitation", "bitter taste in mouth", "sore throat", "chronic cough"],
    "gastroenteritis": ["stomach cramps", "abdominal cramps", "muscle aches", "dehydration", "bloody stools", "diarrhea"],
    "heartattack": ["light-headedness", "jaw pain", "arm pain", "back pain", "indigestion"],
    "hepatitis_a": ["not wanting to eat", "nausea", "upset stomach", "throwing up", "stomach pain", "light colored stools", "diarrhea"],
    "hepatitis_b": ["yellow skin and eyes", "pale stools", "Loss of appetite", "dark urine", "weakness", "whites of the eyes", "malaise", "fluid in the abdomen"],
    "hepatitis_c": ["muscle and joint pain", "poor appetite", "itchy skin", "clay colored stools", "joint swelling", "Pain in the right upper abdomen", "bloating"],
    "hepatitis_d": ["loss of appetite", "pale coloured stools", "yellowing of eyes", "yellow of skin"],
    "hepatitis_e": ["anorexia", "vomiting lasting for a few days", "tender liver", "hepatomegaly", "lack of appetite", "pale faeces"],
    "hypertension": ["dizziness", "shortness of breath", "nosebleeds", "irregular heartbeat", "flushed face", "throbbing headache", "vision changes"],
    "hyperthyroidism": ["increased heart rate", "anxiety", "irritability", "sweating", "tremors", "heat intolerance", "bulging eyes"],
    "hypoglycemia": ["shakiness", "dizziness", "rapid heartbeat", "tingling in mouth", "seizures"],
    "hypothyroidism": ["persistent fatigue", "weight gain", "dry skin", "hair loss", "sensitivity to cold", "muscle weakness", "constipation", "hoarse voice", "brittle nails"],
    "impetigo": ["skin sores", "yellow crusts", "itchiness", "swelling", "red sores", "fluid filled blisters"],
    "jaundice": ["change in skin color", "tiredness ", "yellow skin and white part of the eyes ", "dark urine"],
    "paralysis_brain_hemorrhage": ["loss of movement", "difficulty speaking", "blurred vision", "memory loss", "personality changes", "balance problems"],
    "peptic_ulcer_disease": ["burning sensation in the chest", "bloating", "vomiting blood", "dark or tarry stools", "feeling of fullness"],
    "pneumonia": ["cough", "dehydration", "fast breathing", "sharp in the chest", "green or yellow phlegm", "shaking chills", "clammy skin" ,"hallow breathing", "low energy", "fast heart rate"],
    "psoriasis": ["red patches", "scaling", "thickened or pitted nails", "swollen joints", "small scaling spots"],
    "tuberculosis": ["persistent cough", "weight loss", "coughing up blood", "weakness or fatigue"],
    "typhoid": ["high fever", "diarrhea or constipation", "rose-colored spots on the trunk", "delirium", "slow pulse", "rash"],
    "urinary_tract_infection": ["painful urination", "frequent urination", "cloudy urine", "strong smelling urine", "pelvic pain", "blood in urine", "lower abdominal pain", "back pain"],
    "varicose_veins": ["swollen veins", "leg pain", "itchiness or throbbing in the legs", "skin discoloration", "ulcers on the legs", "heavy or achy feeling in the legs", "muscle cramps", "restless legs", "throbbing or burning in legs", "skin ulcers"],
    "dysentery": ["diarrhea", "blood in stool", "loss of appetite", "weakness", "tenesmus"],
    "amyloidosis": ["tingling or numbness", "enlarged tongue", "skin changes", "heart palpitations", "feeling very weak", "tired", "swelling in the belly", "purple spots", "purpura", "bruised skin around the eyes"],
    "endocarditis": ["swelling in legs or abdomen", "unexplained weight loss", "night sweats", "muscle aches", "petechiae", "changes in heart murmur"],
    "leukemia": ["pale skin", "easy bruising", "frequent infections", "bone pain", "enlarged lymph nodes"],
    "lymphoma": ["swollen lymph nodes", "itching", "abdominal pain or swelling", "shortness of breath", "soaking night sweats", "trouble breathing"],
    "melanoma": ["changes in mole size or color", "itching or tenderness", "bleeding from a mole", "scaliness or oozing", "new moles", "dark bands under nails", "unexplained weight loss", "bone pain"],
    "pancreatitis": ["rapid pulse", "tenderness in abdomen", "swollen abdomen", "low blood pressure"],
    "rabies": ["tingling or twitching at the site of the bite", "agitation", "hallucinations", "hydrophobia", "difficulty swallowing", "paralysis", "excessive salivation"],
    "sickle_cell_anemia": ["painful swelling of hands and feet", "delayed growth", "vision problems", "chest pain", "abdominal swelling", "leg ulcers"],
    "vitiligo": ["loss of skin color", "premature whitening or graying of hair", "eyelashes or eyebrows losing color", "discoloration of tissues inside the nose or mouth", "loss of color in the retina", "photosensitivity", "hearing loss", "change in color of the inner layer of the eye"],
    "zika_virus": ["rash", "conjunctivitis", "muscle pain", "pain behind the eyes", "malaise", "conjunctivitis"],
    "fibroids": ["heavy menstrual bleeding", "constipation", "lower back pain", "pain during intercourse", "leg pains", "anemia"],
    "gastroesophageal_reflux_disease": ["regurgitation", "chronic cough", "hoarseness", "sour taste in mouth", "wheezing", "belching"],
    "hypoparathyroidism": ["hair loss", "dry skin", "brittle nails", "memory problems", "seizures"],
    "inflammatory_bowel_disease": ["weight loss", "bloody stools", "skin rashes", "eye inflammation", "dehydration"],
    "liver_cirrhosis": ["swelling in legs and abdomen", "itchy skin", "confusion", "vomiting blood", "dark urine"],
    "neuropathy": ["burning sensation", "sharp or stabbing pain", "muscle weakness", "difficulty walking", "loss of coordination", "sensitivity to touch", "lack of reflexes", "muscle twitching", "difficulty sleeping"],
    "obstructive_sleep_apnea": ["loud snoring", "choking or gasping during sleep", "excessive daytime sleepiness", "morning headaches", "difficulty concentrating", "irritability", "insomnia", "frequent urination at night", "dry mouth or sore throat upon waking", "high blood pressure"],
    "osteoporosis": ["fractures with minimal trauma", "loss of height", "back pain", "stooped posture", "bone pain or tenderness", "limited mobility", "kyphosis", "curvature of the spine", "brittle nails"],
    "polycystic_ovary_syndrome": ["irregular periods", "excess facial and body hair", "acne", "scalp hair thinning", "weight gain", "anxiety", "insulin resistance", "sleep apnea"],
    "restless_legs_syndrome": ["uncomfortable sensations in legs", "urge to move legs", "worsening of symptoms at rest", "improvement with movement", "difficulty falling asleep", "twitching or jerking of legs during sleep", "daytime fatigue", "anxiety", "difficulty concentrating"],
    "sinusitis": ["facial pain or pressure", "nasal congestion", "runny nose", "loss of smell", "cough", "sore throat", "bad breath"],
    "systemic_lupus_erythematosus": ["skin rashes", "photosensitivity", "swollen glands", "muscle pain", "mouth sores", "kidney problems"],
    "temporo_mandibular_joint_disorder": ["jaw pain tenderness", "popping sounds in the jaw", "ear pain", "neck and shoulder pain", "difficulty opening or closing the mouth", "jaw locking", "dizziness", "toothaches", "ringing in the ears"],
    "uterine_cancer": ["abnormal vaginal bleeding", "pelvic pain", "vaginal discharge", "unexplained weight loss", "loss of appetite", "enlarged uterus", "frequent urination"],
    "fibromyalgia": ["widespread muscle pain", "sleep disturbances", "memory and concentration issues", "chronic", "widespread pain", "muscle tenderness", "mood swings", "painful menstruation"],
    "chronic_myeloid_leukemia": ["unexplained weight loss", "night sweats", "bone pain", "easy bruising or bleeding", "enlarged spleen"],
    "vitamin_deficiency": ["bone pain or tenderness", "low mood", "impaired wound healing", "hair loss", "frequent infections", "poor concentration"],
    "west_nile_virus": ["body aches", "skin rash", "vomiting", "diarrhea", "stiff neck"],
    "celiac_disease": ["bloating", "diarrhea", "irritability", "joint pain", "abdominal pain", "weight loss"],
	"endometriosis": ["painful periods", "heavy menstrual bleeding", "infertility", "pain in pelvis", "pain in rectum", "pain in vagina", "abnormal menstruation"],
    "gout": ["severe joint pain", "redness", "limited range of motion", "warmth over the affected joint", "peeling and itching skin", "kidney stones"],
    "irritable_bowel_syndrome": ["gas", "diarrhea", "constipation", "mucus in stool", "urgency to have a bowel movement", "feeling of incomplete evacuation", "anxiety"],
    "lactose_intolerance": ["bloating", "diarrhea", "stomach cramps", "rumbling or gurgling sounds in the belly", "headaches", "skin rash"],
    "myasthenia_gravis": ["difficulty speaking", "difficulty swallowing", "drooping eyelids", "double vision", "changes in facial expression", "difficulty with limb movement", "poor coordination"],
    "panic_disorder": ["sudden and repeated attacks of fear", "feeling of being out of control", "shortness of breath", "heart palpitations", "trembling", "sweating", "nausea", "tingling or numbness"],
    "rheumatic_fever": ["joint swelling", "rash", "nodules under the skin", "chest pain", "uncontrolled movements"],
    "rosacea": ["flushing or redness in the face", "visible blood vessels", "bumps or pimples", "watery or irritated eyes", "burning or stinging sensation", "thickening of the skin", "facial swelling", "dry or rough skin", "sensitivity to certain skincare products", "eye dryness"],
    "schizoaffective_disorder": ["hallucinations", "delusions", "disorganized thinking", "mood disturbances", "manic episodes", "social withdrawal", "insomnia", "excessive sleep"],
    "tourette_syndrome": ["involuntary repetitive movements or sounds", "facial tics", "blinking", "throat clearing", "grunting", "shoulder shrugging", "sniffling", "head jerking", "touching or tapping", "uncontrollable swearing or obscene gestures"],
    "cushing's_syndrome": ["excess sweating", "excessive hairiness", "excessive hunger", "fatigue", "flushing", "high blood pressure", "loss of muscle", "easy bruising", "potbelly", "reduced sex drive", "round face from gradual swelling", "swelling in extremities"],
    "acoustic_neuroma": ["balance disorder", "dizziness", "hearing loss", "rapid involuntary eye movement", "ringing in ears", "reduced sensation of touch"],
    "prostatitis": ["urinating more often", "burning or stinging during urination", "pain during urination", "chills"],
    "cancer": ["abnormal bumps", "unexplained fevers", "night sweats", "unintentional weight loss", "Unexplained bleeding"],
    "breast_cancer": ["lump in breast", "a lump in armpit", "pain in breast", "bloody discharge from nipple", "changes in shape or texture of nipple", "breast or skin over breast", "swollen lymph nodes", "thickening or puckering of skin"],
    "prostate_cancer": ["difficulty with urination", "pain in bones", "difficulty starting and maintaining a steady stream of urine", "dribbling of urine", "excessive urination at night", "urge to urinate and leaking", "urinary retention", "weak urinary stream"],
    "basal_cell_cancer": ["lesion", "loss of colour", "small bump", "swollen blood vessels in skin", "ulcers", "skin nodules"],
    "colon_cancer": ["pain in abdomen", "blood in stool", "change in bowel habits", "constipation", "narrow stools", "passing excessive amounts of gas", "anemia or fatigue", "abdominal discomfort", "weight loss"],
    "lung_cancer": ["cough often with blood", "chest pain", "wheezing and weight loss", "pain in chest or rib", "frequent respiratory infections", "shortness of breath", "wheezing", "fatigue or loss of appetite", "hoarseness", "weakness"],
    "bladder_cancer": ["blood in urine", "pain during urination", "dark urine", "frequent urination"],
    "sarcoma": ["pain and swelling in an arm or leg", "trunk, pelvis or back", "swelling may or may not feel warm to touch", "a limited range of motion in a joint"],
    "bone_cancer": ["dull", "aching pain", "fracture near the tumor", "pain in bones or joints", "bone fracture", "feeling tired", "limping", "swelling"],
    "anal_cancer": ["lumps around the anus or groin", "ulcers around the anus", "pain", "discomfort", "itching around the anus", "blood or mucus in stools from anus", "difficulty controlling your bowel movements", "feeling of fullness", "discomfort in rectum"],
    "brain_tumor": ["strong headaches", "blurred vision", "weakness of limbs", "loss of balance", "difficulty walking", "weakness of one side of the body", "weakness of the arms and legs", "nausea or vomiting", "pins and needles", "balance disorder", "blurred vision", "difficulty speaking", "personality change", "sleepiness"],
    "myeloma": ["bone pain", "pain in back or bones", "anemia", "hypercalcemia", "increased risk of infection", "kidney damage", "weight loss"],
    "cervical_cancer": ["pain in pelvis", "abnormal menstruation", "heavy menstruation", "irregular menstruation", "spotting", "abnormal vaginal bleeding", "abnormal vaginal discharge"],
    "liver_cancer": ["stomach pain", "vomiting and yellowed skin", "abdomen bloating", "fluid in the abdomen", "cancer related", "itching", "yellow skin", "yellow eyes"],
    "adrenal_cancer": ["weight gain", "trouble sleeping", "deepening voice", "increased hair growth", "pain in abdomen or lower back"],
    "vaginal_cancer": ["pain in pelvic", "pain in rectum", "lump in vagina", "bloody vaginal discharge", "blood in urine", "change in urine colour", "bleeding after sexual intercourse"],
    "hodgkin_lymphoma": ["loss of appetite", "itching", "night sweats", "swollen lymph nodes"],
    "hemochromatosis": ["abdominal pain", "darkening of skin", "weight loss", "diabetes", "enlarged liver"],
    "acanthamoeba_keratitis": ["eye pain", "redness", "sensitivity to light", "excessive tearing", "feeling of something in eye"],
    "stevens_johnson_syndrome": ["painful red or purple rash", "blisters on skin", "mouth sores", "conjunctivitis"],
    "catscratch_fever": ["swollen lymph nodes", "sore throat", "rash", "loss of appetite"],
    "cysticercosis": ["seizures", "cysts in muscles and other tissues", "headaches", "visual disturbances", "neurological symptoms"],
    "hypoplastic_left_heart_syndrome": ["cyanosis", "difficulty breathing", "poor feeding", "cold hands and feet", "lethargy", "weak pulse"],
    "lupus_nephritis": ["joint pain", "fever", "rash", "swelling in legs", "dark urine", "high blood pressure"],
	"pseudotumor_cerebri": ["headaches", "visual disturbances", "nausea", "vomiting", "papilledema", "blurred or double vision", "ringing in the ears"],
    "hereditaryhemorr_hagic_telangiectasia(hht)": ["nosebleeds", "frequent bleeding", "visible blood vessels on skin", "shortness of breath"],
    "celiac_artery_compression_syndrome": ["abdominal pain", "nausea", "vomiting", "blood in stool", "postprandial pain"],
    "chronic_inflammatory_demyelinating_polyneuropathy(cidp)": ["tingling or numbness", "weakness", "difficulty walking", "loss of reflexes", "pain"],
    "epidermolysis_bullosa": ["blisters and sores on skin", "fragile skin", "nail dystrophy", "difficulty swallowing", "dental problems"],
    "stiffskin_syndrome": ["thickening and hardening of the skin", "limited joint mobility", "muscle weakness"],
    "thrombotic_thrombocytopenic_purpura": ["easy bruising", "petechiae", "headache", "kidney failure"],
    "polymyalgia_rheumatica": ["muscle pain and stiffness", "fatigue", "limited range of motion", "unintended weight loss"],
    "kawasaki_disease": ["rash", "redness and swelling of hands and feet", "bloodshot eyes", "strawberry tongue", "swollen lymph nodes"],
    "acute_disseminated_encephalo_myelitis(adem)": ["confusion", "seizures", "weakness", "visual disturbances"],
    "primary_ciliary_dyskinesia": ["chronic cough", "sinus congestion", "ear infections", "infertility", "respiratory distress"],
    "pantothenate_kinase_associated_neurodegeneration(pkan)": ["dystonia", "rigidity", "tremors", "speech difficulties", "visual impairment"],
    "vogt_koyanagi_haradadisease": ["blurred vision", "eye pain", "headaches", "hearing loss", "skin and hair changes"],
    "pemphigus_vulgaris": ["blisters and sores on skin and mucous membranes", "painful mouth sores"],
    "alkaptonuria": ["dark urine", "cartilage and connective tissue discoloration", "heart and kidney problems"],
    "covid_19": ["sore throat", "congestion", "cough", "fatigue", "headache", "fever or chills", "shortness of breath", "difficulty in breathing", "muscle or body aches", "influenza", "human immunodeficiency virus", "dengue fever", "joint and muscle pain", "skin rash"],
    "ebola_virus_disease": ["severe headache", "muscle pain", "diarrhea", "loss of appetite", "coughing blood", "bleeding in vomiting", "red spots on skin"],
    "measles": ["high fever", "cough", "runny nose", "red eyes", "characteristic rash"],
    "mumps": ["swelling of salivary glands", "difficulty chewing", "painful salivary glands", "dry mouth"],
    "rubella": ["mild fever", "rash", "swollen lymph nodes", "low-grade fever", "mild pink eye"],
    "rotavirus": ["severe diarrhea, vomiting in infants and young children"],
    "chikungunya": ["severe joint pain, fever, rash", "headache", "muscle pain"],
    "smallpox": ["high fever", "rash", "pustules", "small bump", "blister", "scab", "scar"],
    "rabies": ["fever", "headache", "muscle spasms", "hydrophobia"],
	"allergic_rhinitis": ["watery eyes", "nasal itching", "allergic cough", "sinus pressure"],
    "asthma": ["breathlessness", "tight chest", "persistent cough", "wheezing"],
    "migraine": ["pulsating headache", "nausea", "light sensitivity", "visual disturbances"],
    "heartburn": ["burning sensation in chest", "acidic taste", "chest discomfort", "indigestion"],
    "flu": ["high fever", "muscle soreness", "severe fatigue", "chills"],
    "bronchitis": ["persistent cough", "mucus production", "chest discomfort", "fatigue"],
    "kidney_stones": ["intense back pain", "blood in urine", "frequent urination", "nausea"],
    "gallstones": ["upper abdominal pain", "vomiting", "indigestion"],
    "osteoarthritis": ["joint pain", "morning stiffness", "swelling", "limited range of motion"],
    "rheumatoid_arthritis": ["swollen joints", "morning stiffness", "fatigue", "joint deformities"],
    "lupus": ["skin rash", "persistent fatigue", "fever", "chest pain"],
    "multiple_sclerosis": ["persistent fatigue", "numbness or tingling", "muscle weakness", "blurred vision"],
    "parkinsons_disease": ["tremors", "rigidity", "bradykinesia", "postural instability"],
    "alzheimers_disease": ["memory loss", "confusion", "difficulty concentrating", "personality changes"],
    "depression": ["persistent sadness", "loss of interest", "changes in appetite", "sleep disturbances"],
    "anxiety_disorder": ["excessive worry", "restlessness", "irritability", "difficulty concentrating"],
    "bipolar_disorder": ["mood swings", "energy fluctuations", "irritable behavior", "racing thoughts"],
    "schizophrenia": ["hallucinations", "delusions", "disorganized thinking", "social withdrawal"],
    "peptic_ulcer": ["abdominal pain", "indigestion", "bloating", "vomiting blood"],
    "crohns_disease": ["abdominal pain", "chronic diarrhea", "weight loss", "fever"],
    "ulcerative_colitis": ["abdominal pain", "bloody stools", "chronic diarrhea", "weight loss"],
    "malaria": ["fever", "chills", "sweating", "headache"],
    "dengue_fever": ["joint pain", "headache", "skin rash", "fever"],
    "ebola": ["fever", "muscle pain", "vomiting", "diarrhea"],
    "hiv_aids": ["persistent fatigue", "fever", "unexplained weight loss", "night sweats"]
}
def find_disease(sentence, dataset):
    matched_diseases = []

    # Convert the sentence to lowercase for case-insensitive comparison
    sentence = sentence.lower().split(',')
    #sentence="high fever cough runny nose red eyes characteristic rash"
    print('sentence ',sentence)
    # Iterate through each disease and its symptoms in the dataset
    for disease, symptoms in dataset.items():
        # Count the number of symptoms present in the sentence
        matched_symptoms = sum(symptom.lower() in sentence for symptom in symptoms)

        # If at least three symptoms are matched, consider it a potential match
        if matched_symptoms >= 4:
            matched_diseases.append(disease)
        if matched_symptoms ==0:
            return 'No diseases found'
    return matched_diseases[0]

# Example usage
sentence_to_check = "rash joint pain muscle pain headache"
print(find_disease(sentence_to_check, dataset))