precautions = {
    "acne": "Keep the skin clean, Avoid squeezing pimples, Use oil-free skincare products, Stay hydrated, Manage stress, Avoid excessive sun exposure, Use non-comedogenic cosmetics",
    "alcoholic_hepatitis": "Quit alcohol consumption, Follow a liver-friendly diet, Get vaccinated for hepatitis, Manage underlying liver conditions, Seek medical advice for alcohol dependence",
    "arthritis": "Apply hot or cold compresses, Consider joint-friendly exercises like swimming, Get enough rest, Maintain a healthy weight, Consider physical therapy",
    "cervical_spondylosis": "Practice neck exercises, Maintain good posture, Use a supportive pillow, Avoid prolonged sitting, Apply heat or cold packs for pain relief",
    "chickenpox": "Trim fingernails to prevent scratching, Take antiviral medications as prescribed, Use calamine lotion for itching, Wear loose-fitting clothing, Stay away from pregnant women",
    "chronic_cholestasis": "Follow a low-fat diet, Take medications as prescribed, Manage itching with cool baths, Avoid alcohol consumption, Attend regular medical check-ups",
    "common_cold": "Stay well-hydrated, Use saline nasal drops, Get plenty of rest, Use over-the-counter cold medications, Gargle with warm saltwater",
    "dengue": "Avoid mosquito bites, Use mosquito repellent, Wear long-sleeved clothing, Keep windows and doors screened, Eliminate mosquito breeding sites",
    "diabetes": "Monitor blood sugar levels regularly, Eat a well-balanced diet, Exercise regularly, Take medications as prescribed, Manage stress",
    "dimorphic_hemorrhoids": "Maintain regular bowel habits, Increase fiber intake, Stay hydrated, Avoid straining during bowel movements, Take warm baths for relief",
    "drug_reaction": "Avoid known allergens, Carry an emergency allergy kit, Wear a medical alert bracelet, Educate caregivers about allergies, Seek emergency medical attention for severe reactions",
    "fungal_infection": "Keep skin clean and dry, Change out of wet clothing promptly, Use antifungal powders, Avoid tight-fitting clothing, Practice good foot hygiene",
    "gerd": "Eat smaller meals, Avoid trigger foods like spicy or acidic items, Elevate the head of the bed, Don't lie down after eating, Maintain a healthy weight",
    "gastroenteritis": "Stay well-hydrated, Eat bland and easily digestible foods, Avoid dairy and caffeine, Practice good hand hygiene, Rest and get plenty of fluids",
    "heartattack": "Know the signs of a heart attack, Call emergency services immediately, Take prescribed medications, Follow a heart-healthy diet, Attend cardiac rehabilitation",
    "hepatitis_a": "Practice good hygiene, Get vaccinated, Avoid contaminated food and water, Wash hands thoroughly, Seek medical attention for symptoms",
    "hepatitis_b": "Get vaccinated, Practice safe sex, Avoid sharing needles, Use sterile equipment for tattoos and piercings, Seek medical attention for symptoms",
    "hepatitis_c": "Practice safe sex, Avoid sharing needles, Use sterile equipment for tattoos and piercings, Seek medical attention for symptoms, Get vaccinated for hepatitis A and B if not immune",
    "hepatitis_d": "Get vaccinated for hepatitis B, Practice safe sex, Avoid sharing needles, Seek medical attention for symptoms",
    "hepatitis_e": "Practice good hygiene, Avoid contaminated food and water, Wash hands thoroughly, Seek medical attention for symptoms, Get vaccinated if traveling to endemic areas",
    "hypertension": "Maintain a healthy weight, Exercise regularly, Follow a low-sodium diet, Limit alcohol intake, Take prescribed medications",
    "hyperthyroidism": "Take prescribed medications, Follow a balanced diet, Manage stress, Avoid excessive caffeine intake, Get regular thyroid function tests",
    "hypoglycemia": "Eat regular meals and snacks, Monitor blood sugar levels, Carry a source of fast-acting sugar, Wear a medical alert bracelet, Inform others about your condition",
    "hypothyroidism": "Take prescribed medications, Follow a balanced diet, Exercise regularly, Manage stress, Get regular thyroid function tests",
    "impetigo": "Keep sores clean and covered, Avoid close contact with others, Wash hands frequently, Take prescribed antibiotics, Avoid scratching sores, Change and wash clothing and linens daily",
    "jaundice": "Treat underlying causes, Follow a liver-friendly diet, Stay hydrated, Avoid alcohol, Get vaccinated for hepatitis A and B if not immune",
    "paralysis_brain_hemorrhage": "Follow a rehabilitation plan, Take prescribed medications, Attend physical therapy, Manage risk factors for recurrence, Seek medical attention for new symptoms",
    "peptic_ulcer_disease": "Follow prescribed medications, Avoid trigger foods, Eat smaller meals, Manage stress, Quit smoking",
    "pneumonia": "Get vaccinated, Practice good hand hygiene, Avoid close contact with sick individuals, Finish prescribed antibiotics, Stay well-hydrated, Follow respiratory hygiene practices",
    "psoriasis": "Avoid triggers like stress and alcohol, Moisturize skin regularly, Use prescribed medications as directed, Get regular sunlight exposure, Seek medical attention for severe symptoms, Consider phototherapy under medical supervision, Follow a healthy diet rich in fruits and vegetables, Manage stress through lifestyle changes, Avoid smoking, Limit alcohol consumption",
    "tuberculosis": "Complete prescribed antibiotic treatment, Practice good respiratory hygiene, Cover mouth when coughing or sneezing, Avoid close contact with others, Get vaccinated if recommended",
    "typhoid": "Practice good hygiene, Consume safe and clean food and water, Wash hands frequently, Get vaccinated, Seek medical attention for symptoms",
    "urinary_tract_infection": "Stay well-hydrated, Urinate regularly, Wipe from front to back after using the toilet, Practice safe sex, Avoid irritants like perfumed soaps in the genital area",
    "varicose_veins": "Maintain a healthy weight, Exercise regularly, Elevate legs when resting, Avoid prolonged periods of standing or sitting, Wear compression stockings",
    "dysentery": "Practice good hygiene, Consume safe and clean food and water, Wash hands frequently, Seek medical attention for severe symptoms, Stay well-hydrated",
    "amyloidosis": "Manage underlying conditions, Follow prescribed medications, Get regular check-ups, Monitor kidney function, Avoid alcohol consumption",
    "endocarditis": "Maintain good oral hygiene, Seek prompt treatment for infections, Take antibiotics before certain dental procedures if advised, Avoid intravenous drug use, Get regular dental check-ups",
    "leukemia": "Follow prescribed treatment plan, Attend regular medical check-ups, Take precautions to avoid infections, Manage fatigue with adequate rest, Follow a healthy diet",
    "lymphoma": "Follow prescribed treatment plan, Attend regular medical check-ups, Take precautions to avoid infections, Manage fatigue with adequate rest, Follow a healthy diet",
    "melanoma": "Practice sun safety, Use sunscreen regularly, Avoid tanning beds, Perform regular skin self-exams, Seek medical attention for changes in moles or skin lesions",
    "pancreatitis": "Limit alcohol consumption, Follow a low-fat diet, Eat small, frequent meals, Stay well-hydrated, Manage underlying conditions",
    "rabies": "Avoid contact with potentially rabid animals, Get vaccinated for rabies if at risk, Seek immediate medical attention for potential exposure, Follow post-exposure prophylaxis if recommended",
    "sickle_cell_anemia": "Stay well-hydrated, Avoid extreme temperatures, Manage stress, Get regular medical check-ups, Follow prescribed medications",
    "vitiligo": "Use sunscreen to protect depigmented skin, Consider camouflage makeup, Manage stress through relaxation techniques, Follow a healthy diet, Seek emotional support",
    "zika_virus": "Avoid mosquito bites, Use insect repellent, Wear protective clothing, Practice safe sex to prevent sexual transmission, Seek medical attention for symptoms",
    "fibroids": "Monitor symptoms and seek medical advice, Manage stress, Follow a healthy diet rich in fruits and vegetables, Stay physically active, Consider medical or surgical interventions if necessary",
    "gastroesophageal_reflux_disease": "Maintain a healthy weight, Avoid trigger foods, Eat smaller meals, Don't lie down after eating, Elevate the head of the bed",
    "hypoparathyroidism": "Take prescribed medications, Get regular calcium and vitamin D levels checked, Follow a balanced diet rich in calcium, Wear a medical alert bracelet, Educate others about the condition",
    "inflammatory_bowel_disease": "Follow prescribed medications, Manage stress through lifestyle changes, Follow a gut-friendly diet, Stay well-hydrated, Attend regular medical check-ups",
    "liver_cirrhosis": "Limit alcohol consumption, Follow a low-sodium diet, Manage underlying conditions, Get vaccinated for hepatitis A and B if not immune, Avoid certain medications",
    "ménière's_disease": "Manage stress, Limit salt intake, Stay hydrated, Avoid caffeine and alcohol, Take prescribed medications as directed",
    "neuropathy": "Manage underlying conditions, Follow prescribed medications, Check feet regularly for injuries, Maintain a healthy lifestyle, Attend regular medical check-ups",
    "obstructive_sleep_apnea": "Maintain a healthy weight, Sleep on your side, Avoid alcohol and sedatives before bedtime, Use continuous positive airway pressure (CPAP) if prescribed, Attend regular follow-ups with a sleep specialist",
    "osteoporosis": "Get enough calcium and vitamin D, Engage in weight-bearing exercises, Quit smoking, Limit alcohol intake, Follow prescribed medications",
    "polycystic_ovary_syndrome": "Maintain a healthy weight, Manage insulin resistance, Follow a balanced diet, Exercise regularly, Seek medical advice for fertility concerns",
    "restless_legs_syndrome": "Maintain a regular sleep schedule, Engage in regular physical activity, Avoid caffeine and alcohol before bedtime, Consider medications if recommended by a healthcare professional, Manage stress",
    "sinusitis": "Practice good nasal hygiene, Use saline nasal sprays, Stay well-hydrated, Apply warm compresses, Avoid irritants like tobacco smoke",
    "systemic_lupus_erythematosus": "Protect skin from sun exposure, Manage stress, Follow prescribed medications, Attend regular medical check-ups, Seek prompt medical attention for flares",
    "temporo_mandibular_joint_disorder": "Practice jaw exercises, Apply ice or heat packs as recommended, Avoid hard or chewy foods, Manage stress, Consider a bite guard for teeth grinding",
    "uterine_cancer": "Attend regular gynecological check-ups, Report abnormal bleeding promptly, Maintain a healthy weight, Follow a balanced diet, Exercise regularly",
    "fibromyalgia": "Practice stress management techniques, Engage in regular, gentle exercise, Get adequate sleep, Establish a regular sleep schedule, Consider physical therapy",
    "chronic_myeloid_leukemia": "Follow prescribed treatment plan, Attend regular medical check-ups, Take precautions to avoid infections, Manage fatigue with adequate rest, Follow a healthy diet",
    "vitamin_deficiency": "Eat a balanced diet rich in vitamins, Consider vitamin supplements if necessary, Get regular exposure to sunlight, Seek medical advice for persistent symptoms",
    "west_nile_virus": "Use insect repellent, Wear protective clothing, Avoid outdoor activities during peak mosquito activity, Eliminate mosquito breeding sites, Seek medical attention for symptoms",
    "celiac_disease": "Follow a strict gluten-free diet, Read food labels carefully, Educate yourself about gluten-containing products, Consider consulting a dietitian, Attend regular check-ups",
    "endometriosis": "Attend regular gynecological check-ups, Report pelvic pain and abnormal menstrual symptoms, Explore pain management strategies, Consider hormonal therapies under medical supervision, Seek emotional support",
    "gout": "Maintain a healthy weight, Follow a low-purine diet, Stay well-hydrated, Limit alcohol consumption, Take medications as prescribed",
    "irritable_bowel_syndrome": "Identify and manage trigger foods, Follow a high-fiber diet, Stay well-hydrated, Manage stress through lifestyle changes, Consider medications under medical supervision",
    "lactose_intolerance": "Limit or avoid dairy products, Consider lactose-free alternatives, Read food labels carefully, Use lactase supplements if necessary, Maintain a balanced diet",
    "myasthenia_gravis": "Follow prescribed medications, Conserve energy during daily activities, Attend regular medical check-ups, Report changes in symptoms promptly, Consider lifestyle modifications for energy conservation",
    "panic_disorder": "Seek psychological counseling, Practice relaxation techniques, Attend cognitive-behavioral therapy, Identify and manage triggers, Consider medications under medical supervision",
    "rheumatic_fever": "Seek prompt treatment for streptococcal infections, Take prescribed antibiotics, Attend regular medical check-ups, Report joint pain promptly, Follow heart health recommendations",
    "rosacea": "Identify and avoid triggers, Use gentle skincare products, Protect skin from sun exposure, Manage stress, Consider prescription medications for symptom control",
    "schizoaffective_disorder": "Follow prescribed medications, Attend psychotherapy sessions, Establish a support system, Monitor mood changes, Seek immediate help for worsening symptoms",
    "tourette_syndrome": "Attend behavioral therapy, Identify and manage triggers, Educate others about the condition, Consider medications under medical supervision, Establish a supportive environment",
    "cushing's_syndrome": "Manage underlying conditions, Follow prescribed medications, Attend regular medical check-ups, Monitor blood pressure, Adopt a healthy lifestyle",
    "acoustic_neuroma": "Seek prompt medical attention for hearing problems, Attend regular ear and hearing check-ups, Consider treatment options under medical supervision",
    "prostatitis": "Practice safe sex, Maintain good hygiene, Stay well-hydrated, Avoid irritants like caffeine and spicy foods, Take prescribed medications",
    "cancer": "Attend regular cancer screenings, Maintain a healthy lifestyle, Avoid tobacco and limit alcohol consumption, Protect skin from sun exposure, Seek medical attention for unusual symptoms",
    "breast_cancer": "Attend regular mammograms, Perform breast self-exams regularly, Report changes in breast tissue promptly, Maintain a healthy lifestyle, Seek genetic counseling if needed",
    "prostate_cancer": "Attend regular prostate screenings, Discuss screening options with a healthcare provider, Maintain a healthy lifestyle, Seek medical attention for urinary symptoms, Consider genetic counseling if needed",
    "basal_cell_cancer": "Protect skin from sun exposure, Perform regular skin self-exams, Report changes in skin lesions promptly, Avoid tanning beds, Seek medical attention for suspicious skin changes",
    "colon_cancer": "Attend regular colonoscopies, Maintain a high-fiber diet, Stay well-hydrated, Avoid tobacco and limit alcohol consumption, Report changes in bowel habits promptly",
    "lung_cancer": "Avoid tobacco and secondhand smoke, Attend regular lung cancer screenings, Protect lungs from occupational hazards, Maintain a healthy lifestyle, Seek medical attention for respiratory symptoms",
    "bladder_cancer": "Stay well-hydrated, Avoid tobacco, Attend regular bladder cancer screenings, Report changes in urinary habits promptly, Maintain a healthy lifestyle",
    "sarcoma": "Seek prompt medical attention for unusual lumps or swelling, Attend regular check-ups with an oncologist, Consider treatment options under medical supervision",
    "bone_cancer": "Seek prompt medical attention for bone pain, Attend regular check-ups with an oncologist, Consider treatment options under medical supervision, Maintain a healthy lifestyle",
    "anal_cancer": "Seek prompt medical attention for anal symptoms, Attend regular check-ups with an oncologist, Consider treatment options under medical supervision, Maintain good hygiene",
    "brain_tumor": "Seek prompt medical attention for neurological symptoms, Attend regular check-ups with a neurologist or oncologist, Consider treatment options under medical supervision, Follow a healthy lifestyle",
    "myeloma": "Follow prescribed treatments, Attend regular check-ups with an oncologist, Manage symptoms with supportive care, Consider lifestyle modifications for symptom control",
    "cervical_cancer": "Attend regular Pap smears and HPV screenings, Discuss vaccination against HPV with a healthcare provider, Maintain a healthy lifestyle, Seek medical attention for abnormal symptoms",
    "liver_cancer": "Attend regular liver cancer screenings, Manage underlying liver conditions, Avoid excessive alcohol consumption, Follow a healthy diet, Seek medical attention for unusual symptoms",
    "adrenal_cancer": "Seek prompt medical attention for adrenal symptoms, Attend regular check-ups with an oncologist, Consider treatment options under medical supervision, Maintain a healthy lifestyle",
    "vaginal_cancer": "Attend regular gynecological check-ups, Report abnormal symptoms promptly, Consider HPV vaccination, Maintain a healthy lifestyle, Seek medical attention for unusual symptoms",
    "hodgkin_lymphoma": "Follow prescribed treatments, Attend regular check-ups with an oncologist, Manage symptoms with supportive care, Consider lifestyle modifications for symptom control",
    "hemochromatosis": "Manage iron levels with regular blood removal, Avoid excessive iron intake, Follow a healthy diet, Attend regular medical check-ups, Consider genetic counseling if needed",
    "acanthamoeba_keratitis": "Practice good eye hygiene, Avoid contaminated water, Use proper contact lens care, Seek prompt medical attention for eye symptoms, Attend regular eye check-ups",
    "stevens_johnson_syndrome": "Avoid known allergens, Discontinue use of suspected medications, Seek immediate medical attention for skin reactions, Attend regular check-ups with a dermatologist",
    "catscratch_fever": "Avoid scratches and bites from cats, Wash cat scratches or bites promptly, Attend regular medical check-ups, Seek medical attention for persistent symptoms, Practice good hygiene around cats",
    "buerger's_disease": "Quit smoking and tobacco use, Maintain a healthy lifestyle, Manage stress, Exercise regularly, Attend regular medical check-ups",
    "cysticercosis": "Practice good hygiene, Cook pork thoroughly before consumption, Avoid contaminated water and food, Maintain sanitation in living spaces, Seek medical attention for symptoms",
    "hypoplastic_left_heart_syndrome": "Attend regular cardiac check-ups, Follow prescribed medications, Monitor for signs of heart failure, Maintain a heart-healthy lifestyle, Seek medical attention for unusual symptoms",
    "lupus_nephritis": "Follow prescribed medications, Attend regular nephrology check-ups, Manage blood pressure and diabetes, Follow a kidney-friendly diet, Stay well-hydrated",
    "pseudotumor_cerebri": "Manage weight through diet and exercise, Follow prescribed medications, Limit sodium intake, Attend regular neurology check-ups, Seek medical attention for worsening symptoms",
    "friedreich's_ataxia": "Engage in physical therapy, Use mobility aids as needed, Attend regular neurology check-ups, Manage heart health, Seek emotional and social support",
    "hereditaryhemorr_hagic_telangiectasia": "Attend regular medical check-ups, Follow prescribed treatments, Manage symptoms with supportive care, Monitor for bleeding symptoms, Seek medical attention for unusual symptoms",
    "celiac_artery_compression_syndrome": "Follow prescribed treatments, Consider surgical options if necessary, Manage pain with medications, Maintain a healthy lifestyle, Attend regular vascular check-ups",
    "chronic_inflammatory_demyelinating_polyneuropathy": "Follow prescribed treatments, Attend regular neurology check-ups, Manage symptoms with supportive care, Consider physical therapy, Seek medical attention for worsening symptoms",
    "epidermolysis_bullosa": "Practice gentle skincare, Use protective bandages, Avoid friction and trauma to the skin, Attend regular dermatology check-ups, Seek medical attention for skin infections",
    "stiffskin_syndrome": "Manage symptoms with physical therapy, Follow prescribed medications, Attend regular rheumatology check-ups, Maintain joint flexibility, Seek medical attention for worsening symptoms",
    "wegener's_granulomatosis": "Follow prescribed medications, Attend regular rheumatology check-ups, Manage symptoms with supportive care, Monitor for respiratory symptoms, Seek medical attention for unusual symptoms",
    "thrombotic_thrombocytopenic_purpura": "Follow prescribed treatments, Attend regular hematology check-ups, Manage symptoms with supportive care, Monitor for bleeding symptoms, Seek medical attention for unusual symptoms",
    "sweet's_syndrome": "Follow prescribed treatments, Attend regular dermatology check-ups, Manage symptoms with supportive care, Monitor for skin lesions, Seek medical attention for unusual symptoms",
    "polymyalgia_rheumatica": "Follow prescribed medications, Attend regular rheumatology check-ups, Engage in gentle exercise, Manage stress, Seek medical attention for worsening symptoms",
    "kawasaki_disease": "Seek prompt medical attention, Follow prescribed treatments, Attend regular pediatric cardiology check-ups, Manage symptoms with supportive care, Monitor for cardiac complications",
    "acute_disseminated_encephalo_myelitis": "Follow prescribed treatments, Attend regular neurology check-ups, Manage symptoms with supportive care, Monitor for neurological symptoms, Seek medical attention for worsening symptoms",
    "primary_ciliary_dyskinesia": "Follow prescribed treatments, Attend regular pulmonology check-ups, Manage respiratory symptoms, Practice airway clearance techniques, Seek medical attention for respiratory infections",
    "pantothenate_kinase_associated_neurodegeneration": "Follow prescribed treatments, Attend regular neurology check-ups, Manage symptoms with supportive care, Consider physical and occupational therapy, Seek medical attention for worsening symptoms",
    "takayasu's_arteritis": "Follow prescribed treatments, Attend regular rheumatology check-ups, Manage blood pressure, Monitor for vascular symptoms, Seek medical attention for worsening symptoms",
    "vogt_koyanagi_haradadisease": "Follow prescribed treatments, Attend regular ophthalmology check-ups, Manage symptoms with supportive care, Monitor for visual disturbances, Seek medical attention for worsening symptoms",
    "pemphigus_vulgaris": "Follow prescribed treatments, Attend regular dermatology check-ups, Manage symptoms with supportive care, Avoid known triggers, Seek medical attention for skin lesions",
    "alkaptonuria": "Follow a low-protein diet, Stay well-hydrated, Attend regular metabolic check-ups, Manage joint symptoms with supportive care, Seek medical attention for worsening symptoms",
    "covid_19": "Follow public health guidelines, Practice good hand hygiene, Wear masks in crowded or indoor settings, Maintain physical distancing, Get vaccinated and stay updated on booster shots",
    "ebola_virus_disease": "Practice strict infection control measures, Avoid contact with blood and body fluids, Wear protective gear, Seek immediate medical attention for symptoms, Follow public health guidelines",
    "measles": "Get vaccinated, Practice good hand hygiene, Avoid close contact with sick individuals, Follow quarantine guidelines if exposed, Seek medical attention for symptoms",
    "mumps": "Get vaccinated, Practice good hand hygiene, Avoid close contact with sick individuals, Use respiratory hygiene, Stay well-hydrated",
    "rubella": "Get vaccinated, Practice good hand hygiene, Avoid close contact with sick individuals, Follow quarantine guidelines if exposed, Seek medical attention for symptoms",
    "rotavirus": "Get vaccinated, Practice good hand hygiene, Avoid close contact with sick individuals, Follow hygiene practices during diaper changing, Stay well-hydrated",
    "chikungunya_virus": "Use mosquito repellent, Wear protective clothing, Eliminate mosquito breeding sites, Seek medical attention for severe symptoms, Stay well-hydrated",
    "smallpox": "Get vaccinated (though smallpox has been eradicated, this precaution was applicable in the past), Practice good hand hygiene, Follow quarantine guidelines if exposed, Seek medical attention for symptoms",
    "rabies": "Avoid contact with potentially rabid animals, Get vaccinated (pre-exposure and post-exposure), Seek immediate medical attention for animal bites, Follow public health guidelines",
    "allergic_rhinitis": "Avoid allergens, Use air purifiers, Keep windows closed during high pollen seasons, Use nasal saline sprays, Take antihistamines",
    "asthma": "Identify and avoid triggers, Use inhalers as prescribed, Maintain a clean living environment, Get regular exercise, Follow an asthma action plan",
    "migraine": "Identify and avoid triggers, Manage stress, Get regular sleep, Stay hydrated, Use prescribed medications",
    "heartburn": "Maintain a healthy weight, Avoid trigger foods, Eat smaller meals, Don't lie down after eating, Elevate the head of the bed",
    "flu": "Get vaccinated, Practice good hand hygiene, Avoid close contact with sick individuals, Cover nose and mouth when coughing or sneezing, Stay well-hydrated",
    "bronchitis": "Quit smoking, Avoid respiratory irritants, Use a humidifier, Get plenty of rest, Stay well-hydrated",
    "kidney_stones": "Stay well-hydrated, Follow a balanced diet, Limit salt intake, Reduce intake of oxalate-rich foods, Seek medical attention for symptoms",
    "gallstones": "Maintain a healthy weight, Eat a balanced diet, Limit cholesterol-rich foods, Avoid rapid weight loss, Seek medical attention for symptoms",
    "osteoarthritis": "Maintain a healthy weight, Exercise regularly, Protect your joints, Use joint-friendly tools and gadgets, Take prescribed medications",
    "rheumatoid_arthritis": "Maintain a healthy weight, Exercise regularly, Protect your joints, Use joint-friendly tools and gadgets, Take prescribed medications",
    "lupus": "Follow prescribed medications, Manage stress, Avoid sun exposure, Get regular exercise, Attend regular rheumatology check-ups",
    "multiple_sclerosis": "Follow prescribed medications, Manage stress, Engage in regular physical activity, Get adequate rest, Attend regular neurology check-ups",
    "parkinsons_disease": "Follow prescribed medications, Engage in regular physical activity, Maintain a healthy diet, Manage stress, Attend regular neurology check-ups",
    "alzheimers_disease": "Maintain cognitive health, Engage in mental exercises, Follow a heart-healthy diet, Stay socially active, Seek medical attention for cognitive decline",
    "depression": "Seek professional help, Engage in social activities, Exercise regularly, Get adequate sleep, Follow prescribed medications",
    "anxiety_disorder": "Seek professional help, Practice relaxation techniques, Engage in regular exercise, Establish a routine, Follow prescribed medications",
    "bipolar_disorder": "Seek professional help, Establish a routine, Get adequate sleep, Engage in regular exercise, Follow prescribed medications",
    "schizophrenia": "Seek professional help, Follow prescribed medications, Engage in supportive therapies, Establish a routine, Involve family and friends in care",
    "peptic_ulcer": "Follow prescribed medications, Avoid trigger foods, Eat smaller meals, Manage stress, Quit smoking",
    "crohns_disease": "Follow prescribed medications, Maintain a healthy diet, Stay well-hydrated, Get regular exercise, Manage stress",
    "ulcerative_colitis": "Follow prescribed medications, Maintain a healthy diet, Stay well-hydrated, Get regular exercise, Manage stress",
    "malaria": "Take antimalarial medications as prescribed, Use bed nets, Wear protective clothing, Use insect repellent, Seek medical attention for symptoms",
    "dengue_fever": "Use mosquito repellent, Wear protective clothing, Eliminate mosquito breeding sites, Seek medical attention for severe symptoms, Stay well-hydrated",
    "ebola": "Practice strict infection control measures, Avoid contact with blood and body fluids, Wear protective gear, Seek immediate medical attention for symptoms, Follow public health guidelines",
    "hiv_aids": "Practice safe sex, Get tested for HIV regularly, Use clean needles for injections, Seek early medical intervention, Follow prescribed antiretroviral therapy"
}
